import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from 'next/dynamic';
import MainPage from "./components/mainPage";
const inter = Inter({ subsets: ["latin"] });

const MapWithNoSSR = dynamic(() => import('./components/map'), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=카카오앱키&autoload=false`}
          async
        />
      </Head>
      <main className={styles.main}>
        <MapWithNoSSR />
      </main>
      <MainPage/>
    </>
  );
}